Zen = {}
Zen.Config = {}

Zen.Jobs = {
    ['unemployed'] = {
        name = 'unemployed',
        label = 'Rage',
        grades = {
            ['0'] = { grade = 0, name = 'unemployed', label = 'Thug', salary = 5000 }
        }
    },

    ['police'] = {
        name = 'police',
        label = 'Police',
        grades = {
            ['1'] = { grade = 0, name = "Cadet", label = "Cadet", salary = 8000 },
            ['2'] = { grade = 1, name = "Officer", label = "Officer", salary = 8000 },
            ['3'] = { grade = 2, name = "Corporal", label = "Corporal", salary = 8000 },
            ['4'] = { grade = 3, name = "Sergeant", label = "Sergeant", salary = 8000 },
            ['5'] = { grade = 4, name = "Lieutenant", label = "Lieutenant", salary = 8000 },
            ['6'] = { grade = 5, name = "Captain", label = "Captain", salary = 8000 },
            ['7'] = { grade = 6, name = "Major", label = "Major", salary = 8000 },
            ['8'] = { grade = 7, name = "Assistant Chief", label = "Assistant Chief", salary = 12000 },
            ['9'] = { grade = 8, name = "Chief of Police", label = "Chief of Police", salary = 16000 },
        }
    },
    
    ['offpolice'] = {
        name = 'offpolice',
        label = 'OFF',
        grades = {
            ['1'] = { grade = 1, name = "Cadet", label = "DUTY", salary = 8000 },
            ['2'] = { grade = 2, name = "Officer", label = "DUTY", salary = 12000 },
            ['3'] = { grade = 3, name = "Corporal", label = "DUTY", salary = 16000 },
            ['4'] = { grade = 4, name = "Sergeant", label = "DUTY", salary = 20000 },
            ['5'] = { grade = 5, name = "Lieutenant", label = "DUTY", salary = 20000 },
            ['6'] = { grade = 6, name = "Captain", label = "DUTY", salary = 20000 },
            ['7'] = { grade = 7, name = "Major", label = "DUTY", salary = 20000 },
            ['8'] = { grade = 8, name = "Assistant Chief", label = "DUTY", salary = 20000 },
            ['9'] = { grade = 9, name = "Chief of Police", label = "DUTY", salary = 50000 }
        }
    },

    ['whitewidow'] = {
        name = 'whitewidow',
        label = 'Whitewidow',
        grades = {
            ['1'] = { grade = 1, name = "worker", label = "Worker", salary = 12000 },
            ['2'] = { grade = 2, name = "owner", label = "Owner", salary = 50000 },
        }
    },

    ['realestate'] = {
        name = 'realestate',
        label = 'Real Estate',
        grades = {
            ['1'] = { grade = 1, name = "agent", label = "Agent", salary = 12000 },
            ['2'] = { grade = 2, name = "manager", label = "Manager", salary = 12000 },
            ['3'] = { grade = 3, name = "owner", label = "Owner", salary = 50000 },
        }
    },

    ['runtz'] = {
        name = 'runtz',
        label = 'Runtz',
        grades = {
            ['1'] = { grade = 1, name = "worker", label = "Worker", salary = 12000 },
            ['2'] = { grade = 2, name = "owner", label = "Owner", salary = 50000 },
        }
    },

    ['vu'] = {
        name = 'vu',
        label = 'Vanilla Unicorn',
        grades = {
            ['0'] = { grade = 0, name = "DJ", label = "DJ", salary = 12000 },
            ['1'] = { grade = 1, name = "Stripper", label = "Stripper", salary = 12000 },
            ['2'] = { grade = 2, name = "Bartender", label = "Bartender", salary = 12000 },
            ['3'] = { grade = 3, name = "Manager", label = "Manager", salary = 12000 },
            ['4'] = { grade = 4, name = "owner", label = "Owner", salary = 50000 },
        }
    },
}

Zen.Items = {
    ["10_off_store_discount"] = { name = "10_off_store_discount", label = "10 off store discount", canRemove = true, limit = 50 },
    ["ansdf"] = { name = "abc123", label = "abc123", canRemove = true, limit = 1 },
    ["Acid"] = { name = "acid", label = "Acid", canRemove = true, limit = 200 },
    ["acid_pooch"] = { name = "acid_pooch", label = "Strips Of Acid", canRemove = true, limit = 20 },
    ["app"] = { name = "app", label = "Apples & Bananas Vape", canRemove = true, limit = -1 },
    ["apple_gelato"] = { name = "apple_gelato", label = "Apple Gelato", canRemove = true, limit = -1 },
    ["apple_gelato_joint"] = { name = "apple_gelato_joint", label = "Apple Gelato Joint", canRemove = true, limit = -1 },
    ["armour"] = { name = "armour", label = "Bullet Proof Vest", canRemove = true, limit = 200 },
    ["backwoods_grape"] = { name = "backwoods_grape", label = "Backwoods Grape", canRemove = true, limit = -1 },
    ["backwoods_honey"] = { name = "backwoods_honey", label = "Backwoods Honey", canRemove = true, limit = -1 },
    ["backwoods_russian_cream"] = { name = "backwoods_russian_cream", label = "Backwoods Russian Cream", canRemove = true, limit = -1 },
    ["banana_backwoods"] = { name = "banana_backwoods", label = "Banana Backwoods", canRemove = true, limit = -1 },
    ["biscotti"] = { name = "biscotti", label = "Biscotti", canRemove = true, limit = -1 },
    ["biscotti_joint"] = { name = "biscotti_joint", label = "Biscotti Joint", canRemove = true, limit = -1 },
    ["blueberry_cruffin"] = { name = "blueberry_cruffin", label = "Blueberry Cruffin", canRemove = true, limit = -1 },
    ["blueberry_cruffin_joint"] = { name = "blueberry_cruffin_joint", label = "Blueberry Cruffin Joint", canRemove = true, limit = -1 },
    ["blueberry_jam_cookie"] = { name = "blueberry_jam_cookie", label = "Blueberry Jam Cookie", canRemove = true, limit = -1 },
    ["blue_tomyz"] = { name = "blue_tomyz", label = "Blue Tomyz", canRemove = true, limit = -1 },
    ["blue_tomyz_joint"] = { name = "blue_tomyz_joint", label = "Blue Tomyz Joint", canRemove = true, limit = -1 },
    ["bourbon"] = { name = "bourbon", label = "Bourbon", canRemove = true, limit = 100 },
    ["bread"] = { name = "bread", label = "Pringles", canRemove = true, limit = 200 },
    ["bumpton"] = { name = "bumpton", label = "Bumpton", canRemove = true, limit = 200 },
    ["butter_cookie"] = { name = "butter_cookie", label = "Butter Cookie", canRemove = true, limit = -1 },
    ["cachaca"] = { name = "cachaca", label = "Cachaca", canRemove = true, limit = 100 },
    ["caipirinha"] = { name = "caipirinha", label = "Caipirinha", canRemove = true, limit = 100 },
    ["cakemix"] = { name = "cakemix", label = "Cake Mix Vape", canRemove = true, limit = -1 },
    ["cake_mix"] = { name = "cake_mix", label = "Cake Mix", canRemove = true, limit = -1 },
    ["cake_mix_joint"] = { name = "cake_mix_joint", label = "Cake Mix Joint", canRemove = true, limit = -1 },
    ["casino_beer"] = { name = "casino_beer", label = "Casino Beer", canRemove = true, limit = -1 },
    ["casino_burger"] = { name = "casino_burger", label = "Casino Burger", canRemove = true, limit = -1 },
    ["casino_chips"] = { name = "casino_chips", label = "Casino Chips", canRemove = true, limit = -1 },
    ["casino_coffee"] = { name = "casino_coffee", label = "Casino Coffee", canRemove = true, limit = -1 },
    ["casino_coke"] = { name = "casino_coke", label = "Casino Kofola", canRemove = true, limit = -1 },
    ["casino_donut"] = { name = "casino_donut", label = "Casino Donut", canRemove = true, limit = -1 },
    ["casino_ego_chaser"] = { name = "casino_ego_chaser", label = "Casino Ego Chaser", canRemove = true, limit = -1 },
    ["casino_luckypotion"] = { name = "casino_luckypotion", label = "Casino Lucky Potion", canRemove = true, limit = -1 },
    ["casino_psqs"] = { name = "casino_psqs", label = "Casino Ps & Qs", canRemove = true, limit = -1 },
    ["casino_sandwitch"] = { name = "casino_sandwitch", label = "Casino Sandwitch", canRemove = true, limit = -1 },
    ["casino_sprite"] = { name = "casino_sprite", label = "Casino Sprite", canRemove = true, limit = -1 },
    ["cereal_milk"] = { name = "cereal_milk", label = "Cereal Milk", canRemove = true, limit = -1 },
    ["cereal_milk_joint"] = { name = "cereal_milk_joint", label = "Cereal Milk Joint", canRemove = true, limit = -1 },
    ["cheap_lighter"] = { name = "cheap_lighter", label = "Cheap Lighter", canRemove = true, limit = -1 },
    ["cheetah_piss"] = { name = "cheetah_piss", label = "Cheetah Piss", canRemove = true, limit = -1 },
    ["cheetah_piss_joint"] = { name = "cheetah_piss_joint", label = "Cheetah Piss Joint", canRemove = true, limit = -1 },
    ["chemicals"] = { name = "chemicals", label = "Chemicals", canRemove = true, limit = 10 },
    ["clip"] = { name = "clip", label = "Weapon Clip", canRemove = true, limit = 200 },
    ["clothing_slots"] = { name = "clothing_slots", label = "Clothing Slot", canRemove = true, limit = 50 },
    ["club_soda"] = { name = "club_soda", label = "Club soda", canRemove = true, limit = 100 },
    ["cmv"] = { name = "cmv", label = "Cereal Milk Vape", canRemove = true, limit = -1 },
    ["coconut_milk"] = { name = "coconut_milk", label = "Coconut milk", canRemove = true, limit = 100 },
    ["cointreau"] = { name = "cointreau", label = "Cointreau", canRemove = true, limit = 100 },
    ["coke"] = { name = "coke", label = "Coke", canRemove = true, limit = 200 },
    ["cokebrick"] = { name = "cokebrick", label = "Coke Brick", canRemove = true, limit = 10 },
    ["coke_pooch"] = { name = "coke_pooch", label = "Coke Pooch", canRemove = true, limit = 10 },
    ["coke_pouch"] = { name = "coke_pouch", label = "Coke Pouch", canRemove = true, limit = 20 },
    ["collins"] = { name = "collins", label = "Collins Ave Vape", canRemove = true, limit = -1 },
    ["collins_ave"] = { name = "collins_ave", label = "Collins AVE", canRemove = true, limit = -1 },
    ["collins_ave_joint"] = { name = "collins_ave_joint", label = "Collins AVE Joint", canRemove = true, limit = -1 },
    ["commoncratekey"] = { name = "commoncratekey", label = "Common Key", canRemove = true, limit = 25 },
    ["common_key"] = { name = "common_key", label = "Common Key", canRemove = true, limit = 999 },
    ["cookie_craze"] = { name = "cookie_craze", label = "Cookie Craze", canRemove = true, limit = -1 },
    ["cosmopolitan"] = { name = "cosmopolitan", label = "Cosmopolitan", canRemove = true, limit = 2 },
    ["cranberry_juice"] = { name = "cranberry_juice", label = "Cranberry juice", canRemove = true, limit = 100 },
    ["curacao"] = { name = "curacao", label = "Orange Curacao liqeur", canRemove = true, limit = 100 },
    ["dark_rum"] = { name = "dark_rum", label = "Dark rum", canRemove = true, limit = 100 },
    ["diamond"] = { name = "diamond", label = "Diamond", canRemove = true, limit = 100 },
    ["donor_car"] = { name = "donor_car", label = "Donor Car Token", canRemove = true, limit = 1 },
    ["double_cup"] = { name = "double_cup", label = "Double cup", canRemove = true, limit = 10 },
    ["ecstasy"] = { name = "ecstasy", label = "Ecstasy", canRemove = true, limit = 200 },
    ["ecstasy_pooch"] = { name = "ecstasy_pooch", label = "Ecstasy Pouch", canRemove = true, limit = 20 },
    ["edible_jollyrancher"] = { name = "edible_jollyrancher", label = "JollyRancher Edible", canRemove = true, limit = 20 },
    ["edible_lm"] = { name = "edible_lm", label = "LaughingMonkey Edible", canRemove = true, limit = 20 },
    ["edible_loops"] = { name = "edible_loops", label = "RainbowLoops Edible", canRemove = true, limit = 20 },
    ["edible_nerds"] = { name = "edible_nerds", label = "Nerd Edible", canRemove = true, limit = 20 },
    ["edible_skittles"] = { name = "edible_skittles", label = "Skittles Edible", canRemove = true, limit = 20 },
    ["edible_starbuds"] = { name = "edible_starbuds", label = "StarBuds Edible", canRemove = true, limit = 20 },
    ["edible_stoneo"] = { name = "edible_stoneo", label = "Stoneo Edible", canRemove = true, limit = 20 },
    ["edible_stoneypatches"] = { name = "edible_stoneypatches", label = "StoneyPatches Edible", canRemove = true, limit = 20 },
    ["empty_cup"] = { name = "empty_cup", label = "Lean cup", canRemove = true, limit = 10 },
    ["empty_lean_bottle"] = { name = "empty_lean_bottle", label = "Empty Lean Bottle", canRemove = true, limit = 10 },
    ["ether"] = { name = "ether", label = "Ether", canRemove = true, limit = -1 },
    ["ether_joint"] = { name = "ether_joint", label = "Ether Joint", canRemove = true, limit = -1 },
    ["fine_china"] = { name = "fine_china", label = "Fine China", canRemove = true, limit = -1 },
    ["fine_china_joint"] = { name = "fine_china_joint", label = "Fine China Joint", canRemove = true, limit = -1 },
    ["flashlight"] = { name = "flashlight", label = "Flashlight", canRemove = true, limit = 1 },
    ["fresh_mix"] = { name = "fresh_mix", label = "Fresh sour mix", canRemove = true, limit = 100 },
    ["froties"] = { name = "froties", label = "Froties", canRemove = true, limit = -1 },
    ["froties_joint"] = { name = "froties_joint", label = "Froties Joint", canRemove = true, limit = -1 },
    ["gang_tier_1"] = { name = "gang_tier_1", label = "Gang Tier 1", canRemove = true, limit = -1 },
    ["gang_tier_3"] = { name = "gang_tier_3", label = "Gang Tier 3", canRemove = true, limit = -1 },
    ["gary"] = { name = "gary", label = "Gary Payton Vape", canRemove = true, limit = -1 },
    ["gary_payton"] = { name = "gary_payton", label = "Gary Payton", canRemove = true, limit = -1 },
    ["gary_payton_joint"] = { name = "gary_payton_joint", label = "Gary Payton Joint", canRemove = true, limit = -1 },
    ["gelatti"] = { name = "gelatti", label = "Gelatti", canRemove = true, limit = -1 },
    ["gelatti_joint"] = { name = "gelatti_joint", label = "Gelatti Joint", canRemove = true, limit = -1 },
    ["georgia_pie"] = { name = "georgia_pie", label = "Georgia Pie", canRemove = true, limit = -1 },
    ["georgia_pie_joint"] = { name = "georgia_pie_joint", label = "Georgia Pie Joint", canRemove = true, limit = -1 },
    ["get_figgy"] = { name = "get_figgy", label = "Get Figgy", canRemove = true, limit = -1 },
    ["gmo_cookies"] = { name = "gmo_cookies", label = "GMO Cookies", canRemove = true, limit = -1 },
    ["gmo_cookies_joint"] = { name = "gmo_cookies_joint", label = "GMO Cookies Joint", canRemove = true, limit = -1 },
    ["gold_rum"] = { name = "gold_rum", label = "Gold rum", canRemove = true, limit = 100 },
    ["grabba_leaf"] = { name = "grabba_leaf", label = "Grabba Leaf", canRemove = true, limit = -1 },
    ["grip"] = { name = "grip", label = "Grip", canRemove = true, limit = 1 },
    ["gsc"] = { name = "gsc", label = "Girl Scout Cookies", canRemove = true, limit = -1 },
    ["halloweenbucket"] = { name = "halloweenbucket", label = "Halloween Bucket", canRemove = true, limit = 1 },
    ["heroin"] = { name = "heroin", label = "Heroin", canRemove = true, limit = 10 },
    ["heroin_shot"] = { name = "heroin_shot", label = "Heroin Shot", canRemove = true, limit = 10 },
    ["ice"] = { name = "ice", label = "Ice", canRemove = true, limit = 100 },
    ["ice_cream_cake_pack"] = { name = "ice_cream_cake_pack", label = "Ice Cream Cake Pack", canRemove = true, limit = -1 },
    ["ice_cream_cake_pack_joint"] = { name = "ice_cream_cake_pack_joint", label = "Ice Cream Cake Pack Joint", canRemove = true, limit = -1 },
    ["jail_free_card"] = { name = "jail_free_card", label = "Get Out Of Comserv Free Card", canRemove = true, limit = 50 },
    ["lean_bottle"] = { name = "lean_bottle", label = "Lean bottle", canRemove = true, limit = 10 },
    ["legendarycratekey"] = { name = "legendarycratekey", label = "Legendary Key", canRemove = true, limit = 10 },
    ["legendary_key"] = { name = "legendary key", label = "Legendary Key", canRemove = true, limit = 999 },
    ["lighter"] = { name = "lighter", label = "Lighter", canRemove = true, limit = -1 },
    ["light_rum"] = { name = "light_rum", label = "Light rum", canRemove = true, limit = 100 },
    ["lime"] = { name = "lime", label = "Lime", canRemove = true, limit = 100 },
    ["limeade"] = { name = "limeade", label = "Limeadge", canRemove = true, limit = 100 },
    ["lockpick"] = { name = "lockpick", label = "Lockpick", canRemove = true, limit = 10 },
    ["london"] = { name = "london", label = "London Pound Vape", canRemove = true, limit = -1 },
    ["mai_tai"] = { name = "mai_tai", label = "Mai Tai", canRemove = true, limit = 100 },
    ["marathon"] = { name = "marathon", label = "Marathon", canRemove = true, limit = -1 },
    ["marathon_joint"] = { name = "marathon_joint", label = "Marathon Joint", canRemove = true, limit = -1 },
    ["margarita"] = { name = "margarita", label = "Margarita", canRemove = true, limit = 100 },
    ["marshmallow_crisp"] = { name = "marshmallow_crisp", label = "Marshmallow Crisp", canRemove = true, limit = -1 },
    ["marshmallow_og"] = { name = "marshmallow_og", label = "Marshmallow OG", canRemove = true, limit = -1 },
    ["marshmallow_og_joint"] = { name = "marshmallow_og_joint", label = "Marshmallow OG Joint", canRemove = true, limit = -1 },
    ["medkit"] = { name = "medkit", label = "Medkit", canRemove = true, limit = 100 },
    ["meth"] = { name = "meth", label = "Crystal Meth", canRemove = true, limit = 200 },
    ["meth_pooch"] = { name = "meth_pooch", label = "Meth Pooch", canRemove = true, limit = 10 },
    ["meth_pouch"] = { name = "meth_pouch", label = "Bag of Crystal Meth", canRemove = true, limit = 20 },
    ["meth_raw"] = { name = "meth_raw", label = "Meth Raw", canRemove = true, limit = 10 },
    ["mint"] = { name = "mint", label = "Mint", canRemove = true, limit = 100 },
    ["mint_julep"] = { name = "mint_julep", label = "Mint Julep", canRemove = true, limit = 100 },
    ["mojito"] = { name = "mojito", label = "Mojito", canRemove = true, limit = 100 },
    ["moon_rock"] = { name = "moon_rock", label = "Moon Rock", canRemove = true, limit = -1 },
    ["moon_rock_joint"] = { name = "moon_rock_joint", label = "Moon Rock Joint", canRemove = true, limit = -1 },
    ["no_99"] = { name = "no_99", label = "NO 99", canRemove = true, limit = -1 },
    ["opium"] = { name = "opium", label = "Opium", canRemove = true, limit = 200 },
    ["opium_pouch"] = { name = "opium_pouch", label = "Opium Pouch", canRemove = true, limit = 20 },
    ["oreoz"] = { name = "oreoz", label = "Oreoz", canRemove = true, limit = -1 },
    ["oreoz_joint"] = { name = "oreoz_joint", label = "Oreoz Joint", canRemove = true, limit = -1 },
    ["paris_fog"] = { name = "paris_fog", label = "Paris Fog", canRemove = true, limit = -1 },
    ["paxton_pearl_cigars"] = { name = "paxton_pearl_cigars", label = "Paxton Pearl Cigars", canRemove = true, limit = -1 },
    ["Ped_Menu_Access"] = { name = "ped_menu_access", label = "ped menu access", canRemove = true, limit = 50 },
    ["perc"] = { name = "perc", label = "Percs", canRemove = true, limit = 200 },
    ["perc_pouch"] = { name = "perc_pouch", label = "Perc Pouch", canRemove = true, limit = 20 },
    ["phone"] = { name = "phone", label = "Phone", canRemove = true, limit = 1 },
    ["pina_colada"] = { name = "pina_colada", label = "Pina Colada", canRemove = true, limit = 100 },
    ["pineapple_juice"] = { name = "pineapple_juice", label = "Pineapple juice", canRemove = true, limit = 100 },
    ["pink_sandy"] = { name = "pink_sandy", label = "Pink Sandy", canRemove = true, limit = -1 },
    ["pink_sandy_joint"] = { name = "pink_sandy_joint", label = "Pink Sandy Joint", canRemove = true, limit = -1 },
    ["pirckly_pear"] = { name = "pirckly_pear", label = "Pirckly Pear", canRemove = true, limit = -1 },
    ["pirckly_pear_joint"] = { name = "pirckly_pear_joint", label = "Pirckly Pear Joint", canRemove = true, limit = -1 },
    ["pogo"] = { name = "pogo", label = "Pogo", canRemove = true, limit = -1 },
    ["pooch_bag"] = { name = "pooch_bag", label = "Pooch Bag", canRemove = true, limit = 10 },
    ["pumpkin_cookie"] = { name = "pumpkin_cookie", label = "Pumpkin Cookie", canRemove = true, limit = -1 },
    ["purplewidow"] = { name = "purplewidow", label = "Purple Widow", canRemove = true, limit = -1 },
    ["Radio"] = { name = "radio", label = "radio", canRemove = true, limit = 1 },
    ["rarecratekey"] = { name = "rarecratekey", label = "Rare Key", canRemove = true, limit = 25 },
    ["rare_key"] = { name = "rare_key", label = "Rare Key", canRemove = true, limit = 50 },
    ["legend_key"] = { name = "legend_key", label = "legend Key", canRemove = true, limit = 50 },
    ["raw_cone_king"] = { name = "raw_cone_king", label = "Raw Cone King", canRemove = true, limit = -1 },
    ["raw_lean"] = { name = "raw_lean", label = "Lean ingredients", canRemove = true, limit = 10 },
    ["repairkit"] = { name = "repairkit", label = "Repairkit", canRemove = true, limit = 25 },
    ["rolex"] = { name = "rolex", label = "Rolex", canRemove = true, limit = 500 },
    ["runtz_og"] = { name = "runtz_og", label = "Runtz OG", canRemove = true, limit = -1 },
    ["runtz_og_joint"] = { name = "runtz_og_joint", label = "Runtz OG Joint", canRemove = true, limit = -1 },
    ["salvia"] = { name = "salvia", label = "Salvia", canRemove = true, limit = 200 },
    ["salvia_pooch"] = { name = "salvia_pooch", label = "Salvia Bag", canRemove = true, limit = 20 },
    ["seed_weed"] = { name = "seed_weed", label = "Weed Seed", canRemove = true, limit = -1 },
    ["shamrock_cookie"] = { name = "shamrock_cookie", label = "Shamrock Cookie", canRemove = true, limit = -1 },
    ["shoes"] = { name = "shoes", label = "Shoes", canRemove = true, limit = 1 },
    ["snow_man"] = { name = "snow_man", label = "Snow Man", canRemove = true, limit = -1 },
    ["snow_man_joint"] = { name = "snow_man_joint", label = "Snow Man Joint", canRemove = true, limit = -1 },
    ["sour_diesel"] = { name = "sour_diesel", label = "Sour Diesel", canRemove = true, limit = -1 },
    ["sour_diesel_joint"] = { name = "sour_diesel_joint", label = "Sour Diesel Joint", canRemove = true, limit = -1 },
    ["spice_leaf"] = { name = "spice_leaf", label = "Spice Leaf", canRemove = true, limit = 10 },
    ["spice_pooch"] = { name = "spice_pooch", label = "Spice Pooch", canRemove = true, limit = 10 },
    ["sticky"] = { name = "sticky", label = "Sticky Buns Vape", canRemove = true, limit = -1 },
    ["strawberry_jam_cookie"] = { name = "strawberry_jam_cookie", label = "Strawberry Jam Cookie", canRemove = true, limit = -1 },
    ["sugar"] = { name = "sugar", label = "Sugar", canRemove = true, limit = 100 },
    ["suppressor"] = { name = "suppressor", label = "Suppressor", canRemove = true, limit = 100 },
    ["syrup"] = { name = "syrup", label = "Orgeat syrup", canRemove = true, limit = 100 },
    ["tahoe_og"] = { name = "tahoe_og", label = "Tahoe OG", canRemove = true, limit = -1 },
    ["tahoe_og_joint"] = { name = "tahoe_og_joint", label = "Tahoe OG Joint", canRemove = true, limit = -1 },
    ["tequila"] = { name = "tequila", label = "Tequila", canRemove = true, limit = 100 },
    ["triple_sec"] = { name = "triple_sec", label = "Triple sec", canRemove = true, limit = 100 },
    ["exotic_key"] = { name = "exotic_key", label = "Exotic key", canRemove = true, limit = 50 },
    ["ped_access"] = { name = "ped_access", label = "Ped Access", canRemove = true, limit = 1 },
    ["20_off_store_discount"] = { name = "20_off_store_discount", label = "20% Off Store Discount", canRemove = true, limit = 2 },
    ["20_off_store_discount"] = { name = "20_off_store_discount", label = "10% Off Store Discount", canRemove = true, limit = 2 },
    ["clothingtier"] = { name = "clothingtier", label = "Clothing Tier", canRemove = true, limit = 2 },
    ["trialmod"] = { name = "trialmod", label = "T-Mod", canRemove = true, limit = 1 },
    ["tunerchip"] = { name = "tunerchip", label = "Tuner Chip", canRemove = true, limit = 1 },
    ["vape"] = { name = "vape", label = "Vape", canRemove = true, limit = -1 },
    ["vodka"] = { name = "vodka", label = "Vodka", canRemove = true, limit = 100 },
    ["water"] = { name = "water", label = "Mellow Yellow - 2 Liters", canRemove = true, limit = 200 },
    ["weapon_appistol"] = { name = "weapon_appistol", label = "AP Pistol", canRemove = true, limit = 1 },
    ["WEAPON_WIENERV2"] = { name = "WEAPON_WIENERV2", label = "WEAPON_WIENERV2", canRemove = true, limit = 1 },
    ["WEAPON_OPIUMWIENER"] = { name = "WEAPON_OPIUMWIENER", label = "WEAPON_OPIUMWIENER", canRemove = true, limit = 1 },
    ["WEAPON_OPIUMAR"] = { name = "WEAPON_OPIUMAR", label = "WEAPON_OPIUMAR", canRemove = true, limit = 1 },
    ["tebex_key"] = { name = "tebex_key", label = "tebex Key", canRemove = false, limit = 10 },
    ["weed"] = { name = "weed", label = "Weed", canRemove = true, limit = 200 },
    ["weed_fertilizer"] = { name = "weed_fertilizer", label = "Weed Fertilizer", canRemove = true, limit = -1 },
    ["weed_leaf"] = { name = "weed_leaf", label = "Weed Leaf", canRemove = true, limit = 10 },
    ["weed_pouch"] = { name = "weed_pouch", label = "Weed Pooch", canRemove = true, limit = 10 },
    ["weed_pot"] = { name = "weed_pot", label = "Weed Pot", canRemove = true, limit = -1 },
    ["weed_seed"] = { name = "weed_seed", label = "Weed Seed", canRemove = true, limit = -1 },
    ["weed_spray"] = { name = "weed_spray", label = "Weed Spray", canRemove = true, limit = -1 },
    ["whitecherry_gelato"] = { name = "whitecherry_gelato", label = "Whitecherry Gelato", canRemove = true, limit = -1 },
    ["whitecherry_gelato_joint"] = { name = "whitecherry_gelato_joint", label = "Whitecherry Gelato Joint", canRemove = true, limit = -1 },
    ["white_rum"] = { name = "white_rum", label = "White rum", canRemove = true, limit = 100 },
    ["white_runtz"] = { name = "white_runtz", label = "White Runtz", canRemove = true, limit = -1 },
    ["white_runtz_joint"] = { name = "white_runtz_joint", label = "White Runtz Joint", canRemove = true, limit = -1 },
    ["xanax"] = { name = "xanax", label = "Xanax", canRemove = true, limit = 200 },
    ["xanax_pouch"] = { name = "xanax_pouch", label = "Bag of Xanax", canRemove = true, limit = 20 },
    ["xpills"] = { name = "xpills", label = "X-Pills", canRemove = true, limit = 10 },
    ["zushi"] = { name = "zushi", label = "Zushi", canRemove = true, limit = -1 },
    ["zushi_joint"] = { name = "zushi_joint", label = "Zushi Joint", canRemove = true, limit = -1 },
    ["cocaine"] = { name = "cocaine", label = "Cocaine", canRemove = true, limit = 200 },
    ["cocaine_pouch"] = { name = "cocaine_pouch", label = "Cocaine Pouch", canRemove = true, limit = 20 },
    ["codiene"] = { name = "codiene", label = "Codiene", canRemove = true, limit = 200 },
    ["codiene_pouch"] = { name = "codiene_pouch", label = "Codiene Pouch", canRemove = true, limit = 20 },
    ["lean"] = { name = "lean", label = "Lean", canRemove = true, limit = 200 },
    ["lean_pouch"] = { name = "lean_pouch", label = "Lean Pouch", canRemove = true, limit = 20 },
    ["percocet"] = { name = "percocet", label = "Percocet", canRemove = true, limit = 200 },
    ["percocet_pouch"] = { name = "percocet_pouch", label = "Percocet Pouch", canRemove = true, limit = 20 },
    ["Burger"] = { name = "Burger", label = "Burger", canRemove = true, limit = 200 },
    ["Burger_pouch"] = { name = "Burger_pouch", label = "Burger Pouch", canRemove = true, limit = 20 },
    ["uncomserv_card"] = { name = "uncomserv_card", label = "Uncomserv Card", canRemove = true, limit = 20 },
    ["limted_car_token"] = { name = "limted_car_token", label = "limted token", canRemove = true, limit = 20 },
}


-- you do not need to touch ANY of these
Zen.Accounts = { ['black_money'] = 'Dirty Cash', ['bank'] = 'Bank', ['money'] = 'Cash' }
Zen.Keys = { ["A"] = 34, ["B"] = 29, ["C"] = 26, ["D"] = 30, ["E"] = 38, ["F"] = 23, ["G"] = 47, ["H"] = 74, ["I"] = 20, ["J"] = 36, ["K"] = 37, ["L"] = 38, ["M"] = 32, ["N"] = 49, ["O"] = 24, ["P"] = 25, ["Q"] = 44, ["R"] = 45, ["S"] = 33, ["T"] = 23, ["U"] = 303, ["V"] = 0, ["W"] = 32, ["X"] = 73, ["Y"] = 246, ["Z"] = 20, ["0"] = 11, ["1"] = 157, ["2"] = 158, ["3"] = 160, ["4"] = 164, ["5"] = 165, ["6"] = 159, ["7"] = 161, ["8"] = 162, ["9"] = 163, ["~"] = 243, ["-"] = 84, ["="] = 83, ["Backspace"] = 177, ["Tab"] = 37, ["CapsLock"] = 137, ["Enter"] = 176, ["Shift"] = 21, ["Ctrl"] = 36, ["Alt"] = 19, ["Pause"] = 22, ["PageUp"] = 10, ["PageDown"] = 11, ["End"] = 30, ["Home"] = 36, ["Insert"] = 73, ["Delete"] = 76, ["UpArrow"] = 32, ["DownArrow"] = 33, ["LeftArrow"] = 34, ["RightArrow"] = 35, ["F1"] = 288, ["F2"] = 289, ["F3"] = 170, ["F4"] = 166, ["F5"] = 167, ["F6"] = 168, ["F7"] = 169, ["F8"] = 56, ["F9"] = 57, ["F10"] = 344, ["F11"] = 345, ["F12"] = 346, ["NumLock"] = 37, ["ScrollLock"] = 70, [";"] = 74, [","] = 51, ["."] = 72, ["/"] = 45, ["'"] = 243, ["["] = 44, ["]"] = 32, ["\\"] = 36 }
Zen.Weapons = { ['weapon_unarmed'] = 'Fists', ['weapon_knife'] = 'Knife', ['weapon_nightstick'] = 'Nightstick', ['WEAPON_CANDYAXE'] = 'WEAPON_CANDYAXE', ['weapon_bat'] = 'Baseball Bat', ['weapon_golfclub'] = 'Golf Club', ['weapon_crowbar'] = 'Crowbar', ['weapon_pistol'] = 'Pistol', ['weapon_combatpistol'] = 'Combat Pistol', ['weapon_appistol'] = 'AP Pistol', ['weapon_pistol50'] = 'Pistol .50', ['weapon_microsmg'] = 'Micro SMG', ['weapon_smg'] = 'SMG', ['weapon_assaultsmg'] = 'Assault SMG', ['weapon_assaultrifle'] = 'Assault Rifle', ['weapon_carbinerifle'] = 'Carbine Rifle', ['WEAPON_OPIUMAR'] = 'Opium AR', ['WEAPON_OPIUMWIENER'] = 'OPIUMWIENER', ['weapon_combatmg'] = 'Combat MG', ['weapon_pumpshotgun'] = 'Pump Shotgun', ['weapon_sawnoffshotgun'] = 'Sawed-Off Shotgun', ['weapon_assaultshotgun'] = 'Assault Shotgun', ['weapon_bullpupshotgun'] = 'Bullpup Shotgun', ['weapon_stungun'] = 'Stun Gun', ['weapon_sniperrifle'] = 'Sniper Rifle', ['weapon_heavysniper'] = 'Heavy Sniper', ['weapon_grenadelauncher'] = 'Grenade Launcher', ['weapon_rpg'] = 'RPG', ['weapon_minigun'] = 'Minigun', ['weapon_grenade'] = 'Grenade', ['weapon_stickybomb'] = 'Sticky Bomb', ['weapon_smokegrenade'] = 'Smoke Grenade', ['weapon_bzgas'] = 'BZ Gas', ['weapon_molotov'] = 'Molotov Cocktail', ['weapon_fireextinguisher'] = 'Fire Extinguisher', ['weapon_petrolcan'] = 'Jerry Can', ['weapon_ball'] = 'Baseball', ['weapon_snspistol'] = 'SNS Pistol', ['weapon_bottle'] = 'Broken Bottle', ['weapon_gusenberg'] = 'Gusenberg Sweeper', ['weapon_specialcarbine'] = 'Special Carbine', ['weapon_heavypistol'] = 'Heavy Pistol', ['weapon_bullpuprifle'] = 'Bullpup Rifle', ['weapon_dagger'] = 'Dagger', ['weapon_vintagepistol'] = 'Vintage Pistol', ['weapon_firework'] = 'Firework Launcher', ['weapon_musket'] = 'Musket', ['weapon_heavyshotgun'] = 'Heavy Shotgun', ['weapon_marksmanrifle'] = 'Marksman Rifle', ['weapon_hominglauncher'] = 'Homing Launcher', ['weapon_proxmine'] = 'Proximity Mines', ['weapon_snowball'] = 'Snowball', ['weapon_flaregun'] = 'Flare Gun', ['weapon_garbagebag'] = 'Garbage Bag', ['weapon_handcuffs'] = 'Handcuffs', ['weapon_combatpdw'] = 'Combat PDW', ['weapon_marksmanpistol'] = 'Marksman Pistol', ['weapon_knuckle'] = 'Knuckle Dusters', ['weapon_hatchet'] = 'Hatchet', ['weapon_railgun'] = 'Railgun', ['weapon_machete'] = 'Machete', ['weapon_machinepistol'] = 'Machine Pistol', ['weapon_switchblade'] = 'Switchblade', ['weapon_revolver'] = 'Heavy Revolver', ['weapon_heavyrifle'] = 'Heavy Rifle', ['weapon_dbshotgun'] = 'Double Barrel Shotgun', ['WEAPON_WIENERV2'] = 'WEAPON_WIENERV2', ['weapon_autoshotgun'] = 'Sweeper Shotgun', ['weapon_battleaxe'] = 'Battle Axe', ['weapon_compactlauncher'] = 'Compact Grenade Launcher', ['weapon_minismg'] = 'Mini SMG', ['weapon_pipebomb'] = 'Pipe Bomb', ['weapon_poolcue'] = 'Pool Cue', ['weapon_wrench'] = 'Wrench', ['weapon_autoshotgun'] = 'Sweeper Shotgun', ['weapon_bread'] = 'Piece of Bread', ['weapon_stone_hatchet'] = 'Stone Hatchet', ['weapon_hominglauncher'] = 'Homing Launcher', ['weapon_rayminigun'] = 'Unholy Hellbringer', ['weapon_raycarbine'] = 'Widowmaker', ['weapon_bzgas'] = 'BZ Gas', ['weapon_compactgrenadelauncher'] = 'Compact Grenade Launcher', ['weapon_smugglerpistol'] = 'Up-n-Atomizer', ['weapon_raypistol'] = 'Pistol .50', ['weapon_perico_pistol'] = 'Ceramic Pistol', ['weapon_carbinerifle_mk2'] = 'Carbine Rifle Mk II', ['weapon_combatmg_mk2'] = 'Combat MG Mk II', ['weapon_heavysniper_mk2'] = 'Heavy Sniper Mk II', ['weapon_marksmanrifle_mk2'] = 'Marksman Rifle Mk II', ['weapon_pumpshotgun_mk2'] = 'Pump Shotgun Mk II', ['weapon_smg_mk2'] = 'SMG Mk II', ['weapon_raycarbine_mk2'] = 'Widowmaker Mk II', ['weapon_machete'] = 'Machete', ['weapon_flashlight'] = 'Flashlight', ['weapon_hazardousknife'] = 'Hazardous Knife', ['weapon_navyrevolver'] = 'Navy Revolver', ['weapon_ball'] = 'Baseball', ['weapon_golfball'] = 'Golf Ball', ['weapon_snowball'] = 'Snowball', ['weapon_paintball'] = 'Paintball Gun', ['WEAPON_SIG516'] = 'SIG516', ['WEAPON_DRACO'] = 'Mini Draco', ['WEAPON_MP5'] = 'MP5', ['WEAPON_BARRETT'] = 'Barret 50', ['WEAPON_G18C'] = 'Glock 18c', ['WEAPON_MAC'] = 'Mac 10' }
Zen.HashKey = { [1317494643] = "WEAPON_CANDYAXE", [2024373456] = "weapon_smg_mk2", [-1654528753] = "weapon_bullpupshotgun", [2132975508] = "weapon_bullpuprifle", [1980066947] = "weapon_compactgrenadelauncher", [1627465347] = "weapon_gusenberg", [-270015777] = "weapon_assaultsmg", [317205821] = "weapon_autoshotgun", [-1063057011] = "weapon_specialcarbine", [1593441988] = "weapon_combatpistol", [-1501891397] = "weapon_smugglerpistol", [-1398540680] = "weapon_perico_pistol", [419712736] = "weapon_wrench", [-598887786] = "weapon_marksmanpistol", [1119849093] = "weapon_minigun", [-1716589765] = "weapon_pistol50", [-37975472] = "weapon_smokegrenade", [-771403250] = "weapon_heavypistol", [-1786099057] = "weapon_bat", [2017895192] = "weapon_sawnoffshotgun", [125959754] = "weapon_compactlauncher", [-1569615261] = "weapon_unarmed", [1309015656] = "weapon_bread", [-538741184] = "weapon_switchblade", [-947031628] = "weapon_heavyrifle", [1834241177] = "weapon_railgun", [-1074790547] = "weapon_assaultrifle", [-952879014] = "weapon_marksmanrifle", [-1660422300] = "WEAPON_OPIUMWIENER", [-1076751822] = "weapon_snspistol", [-499989876] = "weapon_garbagebag", [-809611085] = "weapon_raycarbine_mk2", [-619010992] = "weapon_machinepistol", [-1814108143] = "weapon_hazardousknife", [-494615257] = "weapon_assaultshotgun", [-1357824103] = "WEAPON_OPIUMAR", [-1600701090] = "weapon_bzgas", [-656458692] = "weapon_knuckle", [-1951375401] = "weapon_flashlight", [-2067956739] = "weapon_crowbar", [1432025498] = "weapon_pumpshotgun_mk2", [100416529] = "weapon_sniperrifle", [1785463520] = "weapon_marksmanrifle_mk2", [177293209] = "weapon_heavysniper_mk2", [-608341376] = "weapon_combatmg_mk2", [-86904375] = "weapon_carbinerifle_mk2", [-1355376991] = "weapon_raypistol", [2144741730] = "weapon_combatmg", [1649403952] = "WEAPON_WIENERV2", [-1238556825] = "weapon_rayminigun", [1141786504] = "weapon_golfclub", [584646201] = "weapon_appistol", [984333226] = "weapon_heavyshotgun", [-1810795771] = "weapon_poolcue", [-1169823560] = "weapon_pipebomb", [205991906] = "weapon_heavysniper", [1737195953] = "weapon_nightstick", [-1121678507] = "weapon_minismg", [1672152130] = "weapon_hominglauncher", [-1716189206] = "weapon_knife", [453432689] = "weapon_pistol", [-853065399] = "weapon_battleaxe", [1198256469] = "weapon_raycarbine", [-2084633992] = "weapon_carbinerifle", [-102323637] = "weapon_bottle", [-1045183535] = "weapon_revolver", [-1420407917] = "weapon_proxmine", [-1834847097] = "weapon_dagger", [-1312131151] = "weapon_rpg", [-102973651] = "weapon_hatchet", [171789620] = "weapon_combatpdw", [-800287667] = "weapon_handcuffs", [615608432] = "weapon_molotov", [126349499] = "weapon_snowball", [600439132] = "weapon_ball", [736523883] = "weapon_smg", [-209057321] = "weapon_golfball", [324215364] = "weapon_microsmg", [-1568386805] = "weapon_grenadelauncher", [741814745] = "weapon_stickybomb", [-1466123874] = "weapon_musket", [940833800] = "weapon_stone_hatchet", [2138347493] = "weapon_firework", [911657153] = "weapon_stungun", [-275439685] = "weapon_dbshotgun", [883325847] = "weapon_petrolcan", [101631238] = "weapon_fireextinguisher", [1198879012] = "weapon_flaregun", [487013001] = "weapon_pumpshotgun", [-581044007] = "weapon_machete", [-1813897027] = "weapon_grenade", [137902532] = "weapon_vintagepistol", [-1853920116] = "weapon_navyrevolver" }
Zen.Counter = { ['Hour'] = 3600, ['Day'] = 86400, ['Week'] = 604800, ['Month'] = 2592000, ['Year'] = 31536000 }

exports('getJobs', function() return Zen.Jobs end)
exports('getItems', function() return Zen.Items end)
exports('getAccounts', function() return Zen.Accounts end)